---

- name: Upgrade all packages
  apt:
    name: '*'
    state: latest

- name: Install some packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - htop
    - sudo
    - python3-psycopg2
    - zip
    - pip